export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  INSTITUTION_ADMIN: 'INSTITUTION_ADMIN',
  STAFF: 'INSTITUTION_STAFF',
  VIEWER: 'INSTITUTION_VIEWER',
  COACH: 'COACH',
  SOCIO: 'SOCIO',
};

export const PERMISSIONS = {
  // Dashboard
  VIEW_DASHBOARD: 'view_dashboard',
  VIEW_COACH_DASHBOARD: 'view_coach_dashboard',
  VIEW_SOCIO_DASHBOARD: 'view_socio_dashboard',

  // Courts
  VIEW_COURTS: 'view_courts',
  MANAGE_COURTS: 'manage_courts',

  // Reservations
  VIEW_RESERVATIONS: 'view_reservations',
  MANAGE_RESERVATIONS: 'manage_reservations',
  CREATE_RESERVATION: 'create_reservation',
  DELETE_RESERVATION: 'delete_reservation',
  EDIT_RESERVATION: 'edit_reservation',

  // Schedule
  VIEW_SCHEDULE: 'view_schedule',
  MANAGE_SCHEDULE: 'manage_schedule',

  // Users
  VIEW_USERS: 'view_users',
  MANAGE_USERS: 'manage_users',
  MANAGE_STUDENTS: 'manage_students', // Specific for coaches

  // Pricing
  VIEW_PRICING: 'view_pricing',
  MANAGE_PRICING: 'manage_pricing',

  // Reports/Stats
  VIEW_REPORTS: 'view_reports',
  VIEW_STATS: 'view_stats',

  // Tournaments
  VIEW_TOURNAMENTS: 'view_tournaments',
  MANAGE_TOURNAMENTS: 'manage_tournaments',
  
  // Settings
  VIEW_SETTINGS: 'view_settings',
  // Coach specific
  MANAGE_OWN_AVAILABILITY: 'manage_own_availability',
  MANAGE_COACH_QUOTAS: 'manage_coach_quotas',
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    ...Object.values(PERMISSIONS), // All permissions
  ],

  [ROLES.INSTITUTION_ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_COURTS, PERMISSIONS.MANAGE_COURTS,
    PERMISSIONS.VIEW_RESERVATIONS, PERMISSIONS.MANAGE_RESERVATIONS, PERMISSIONS.CREATE_RESERVATION, PERMISSIONS.DELETE_RESERVATION, PERMISSIONS.EDIT_RESERVATION,
    PERMISSIONS.VIEW_SCHEDULE, PERMISSIONS.MANAGE_SCHEDULE,
    PERMISSIONS.VIEW_USERS, PERMISSIONS.MANAGE_USERS, PERMISSIONS.MANAGE_COACH_QUOTAS,
    PERMISSIONS.VIEW_PRICING, PERMISSIONS.MANAGE_PRICING,
    PERMISSIONS.VIEW_REPORTS, PERMISSIONS.VIEW_STATS,
    PERMISSIONS.VIEW_TOURNAMENTS, PERMISSIONS.MANAGE_TOURNAMENTS,
    PERMISSIONS.VIEW_SETTINGS, PERMISSIONS.MANAGE_SETTINGS,
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_COURTS,
    PERMISSIONS.VIEW_RESERVATIONS, PERMISSIONS.MANAGE_RESERVATIONS, PERMISSIONS.CREATE_RESERVATION, PERMISSIONS.EDIT_RESERVATION,
    PERMISSIONS.VIEW_SCHEDULE, PERMISSIONS.MANAGE_SCHEDULE,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_PRICING,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_COURTS,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.VIEW_SCHEDULE,
    PERMISSIONS.VIEW_PRICING,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.COACH]: [
    PERMISSIONS.VIEW_COACH_DASHBOARD,
    // PERMISSIONS.VIEW_SCHEDULE, // Removed: Coaches have their own availability page
    PERMISSIONS.MANAGE_OWN_AVAILABILITY, // New permission
    PERMISSIONS.VIEW_RESERVATIONS, // Can view own reservations
    PERMISSIONS.CREATE_RESERVATION, // Can create reservations
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.VIEW_TOURNAMENTS,
    PERMISSIONS.VIEW_STATS,
  ],
  [ROLES.SOCIO]: [
    PERMISSIONS.VIEW_SOCIO_DASHBOARD,
    PERMISSIONS.VIEW_RESERVATIONS, // Can view own reservations
    PERMISSIONS.CREATE_RESERVATION, // Can create reservations
  ],
};
